[project]
name = 'stackpay'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST1H7G0B7BBM991P2KA77R0XHDRNYCWH8H92TT4QN.architecturexx'
[contracts.architecturexx]
path = 'contracts/architecturexx.clar'
clarity_version = 4
epoch = 'latest'

[contracts.processorxxx]
path = 'contracts/processorxxx.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
